-- ============================================================
-- central_routing_tests.sql
-- Demonstration du routage automatique depuis oracle-central
-- A executer sur BDDCENTRAL avec l'utilisateur eshopcentral.
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 220
SET PAGESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET WRAP OFF

COLUMN SITE FORMAT A6
COLUMN OPERATION FORMAT A12
COLUMN SITE_CIBLE FORMAT A10
COLUMN DATE_OP FORMAT A19
COLUMN UTILISATEUR FORMAT A14
COLUMN IDLIGNECOMMANDE FORMAT 9999999999 HEADING ID_LIGNE
COLUMN IDCOMMANDE FORMAT 999999999 HEADING ID_CMD
COLUMN IDPRODUIT FORMAT 999999999 HEADING ID_PROD
COLUMN QUANTITE FORMAT 9999999 HEADING QTE
COLUMN REMISE FORMAT 990.99
COLUMN NB_SITE1 FORMAT 999999 HEADING SITE1
COLUMN NB_SITE2 FORMAT 999999 HEADING SITE2

PROMPT === Nettoyage eventuel de la ligne de test ===
BEGIN
    BEGIN
        route_delete_ligne(9001);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -20104 THEN
                RAISE;
            END IF;
    END;
    DELETE FROM ROUTING_LOG
    WHERE IDLIGNECOMMANDE = 9001;
    COMMIT;
END;
/

PROMPT === INSERT via vue centrale : QUANTITE >= 100 doit aller vers SITE1 ===
INSERT INTO V_LIGNECOMMANDES_ROUTAGE
    (IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE)
VALUES
    (9001, 1, 1, 150, 0);
COMMIT;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE
WHERE IDLIGNECOMMANDE = 9001;

PROMPT === UPDATE via vue centrale : QUANTITE < 100 doit deplacer vers SITE2 ===
UPDATE V_LIGNECOMMANDES_ROUTAGE
SET QUANTITE = 25,
    IDPRODUIT = 2,
    REMISE = 0.05
WHERE IDLIGNECOMMANDE = 9001
  AND SITE = 'SITE1';
COMMIT;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE
WHERE IDLIGNECOMMANDE = 9001;

PROMPT === Verification absence de doublon entre les deux sites ===
SELECT
    (SELECT COUNT(*) FROM LigneCommandes1@site1_link WHERE IDLIGNECOMMANDE = 9001) AS NB_SITE1,
    (SELECT COUNT(*) FROM LigneCommandes2@site2_link WHERE IDLIGNECOMMANDE = 9001) AS NB_SITE2
FROM dual;

PROMPT === DELETE via vue centrale ===
DELETE FROM V_LIGNECOMMANDES_ROUTAGE
WHERE IDLIGNECOMMANDE = 9001
  AND SITE = 'SITE2';
COMMIT;

SELECT
    ID_LOG,
    OPERATION,
    SITE_CIBLE,
    IDLIGNECOMMANDE,
    IDCOMMANDE,
    IDPRODUIT,
    QUANTITE,
    TO_CHAR(DATE_OPERATION, 'DD/MM/YYYY HH24:MI:SS') AS DATE_OP,
    UTILISATEUR
FROM ROUTING_LOG
WHERE IDLIGNECOMMANDE = 9001
ORDER BY ID_LOG;
