-- ============================================================
-- central_routing_sc1_tests.sql
-- Demonstration du routage automatique Scenario 1 depuis central
-- Regle :
--   - IDCATEG = 50 -> Site1
--   - IDCATEG = 35 -> Site2
-- A executer sur BDDCENTRAL avec l'utilisateur eshopcentral,
-- apres avoir deploye les fragments scenario1.
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 220
SET PAGESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET WRAP OFF

COLUMN SITE FORMAT A6
COLUMN OPERATION FORMAT A12
COLUMN SITE_CIBLE FORMAT A10
COLUMN DATE_OP FORMAT A19
COLUMN UTILISATEUR FORMAT A14
COLUMN IDLIGNECOMMANDE FORMAT 9999999999 HEADING ID_LIGNE
COLUMN IDCOMMANDE FORMAT 999999999 HEADING ID_CMD
COLUMN IDPRODUIT FORMAT 999999999 HEADING ID_PROD
COLUMN QUANTITE FORMAT 9999999 HEADING QTE
COLUMN REMISE FORMAT 990.99
COLUMN NB_SITE1 FORMAT 999999 HEADING SITE1
COLUMN NB_SITE2 FORMAT 999999 HEADING SITE2

PROMPT === Nettoyage eventuel de la ligne de test sc1 ===
BEGIN
    BEGIN
        route_delete_ligne_sc1(9002);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -20206 THEN
                RAISE;
            END IF;
    END;
    DELETE FROM ROUTING_LOG
    WHERE IDLIGNECOMMANDE = 9002;
    COMMIT;
END;
/

PROMPT === INSERT sc1 : produit IDCATEG=50 doit aller vers SITE1 ===
INSERT INTO V_LIGNECOMMANDES_ROUTAGE_SC1
    (IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE)
VALUES
    (9002, 1, 1, 20, 0);
COMMIT;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE_SC1
WHERE IDLIGNECOMMANDE = 9002;

PROMPT === UPDATE sc1 : produit IDCATEG=35 doit deplacer vers SITE2 ===
UPDATE V_LIGNECOMMANDES_ROUTAGE_SC1
SET IDCOMMANDE = 6,
    IDPRODUIT = 4,
    QUANTITE = 150,
    REMISE = 0.05
WHERE IDLIGNECOMMANDE = 9002
  AND SITE = 'SITE1';
COMMIT;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE_SC1
WHERE IDLIGNECOMMANDE = 9002;

PROMPT === Verification absence de doublon sc1 entre les deux sites ===
SELECT
    (SELECT COUNT(*) FROM LigneCommandes1_sc1@site1_link WHERE IDLIGNECOMMANDE = 9002) AS NB_SITE1,
    (SELECT COUNT(*) FROM LigneCommandes2_sc1@site2_link WHERE IDLIGNECOMMANDE = 9002) AS NB_SITE2
FROM dual;

PROMPT === DELETE sc1 via vue centrale ===
DELETE FROM V_LIGNECOMMANDES_ROUTAGE_SC1
WHERE IDLIGNECOMMANDE = 9002
  AND SITE = 'SITE2';
COMMIT;

SELECT
    ID_LOG,
    OPERATION,
    SITE_CIBLE,
    IDLIGNECOMMANDE,
    IDCOMMANDE,
    IDPRODUIT,
    QUANTITE,
    TO_CHAR(DATE_OPERATION, 'DD/MM/YYYY HH24:MI:SS') AS DATE_OP,
    UTILISATEUR
FROM ROUTING_LOG
WHERE IDLIGNECOMMANDE = 9002
ORDER BY ID_LOG;
