-- ============================================================
-- central_direct_table_routing_tests.sql
-- Test du routage automatique quand on ecrit directement dans
-- la table centrale LIGNECOMMANDES.
--
-- Scenario 2 par defaut :
--   - QUANTITE >= 100 -> Site1
--   - QUANTITE < 100  -> Site2
--
-- A executer sur BDDCENTRAL avec l'utilisateur eshopcentral.
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 220
SET PAGESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET WRAP OFF

COLUMN SITE FORMAT A6
COLUMN OPERATION FORMAT A12
COLUMN SITE_CIBLE FORMAT A10
COLUMN IDLIGNECOMMANDE FORMAT 9999999999 HEADING ID_LIGNE
COLUMN IDCOMMANDE FORMAT 999999999 HEADING ID_CMD
COLUMN IDPRODUIT FORMAT 999999999 HEADING ID_PROD
COLUMN QUANTITE FORMAT 9999999 HEADING QTE
COLUMN REMISE FORMAT 990.99
COLUMN NB_CENTRAL FORMAT 999999 HEADING CENTRAL
COLUMN NB_SITE1 FORMAT 999999 HEADING SITE1
COLUMN NB_SITE2 FORMAT 999999 HEADING SITE2

PROMPT === Nettoyage eventuel de la ligne directe de test ===
ALTER TRIGGER trg_route_lignecommandes_table DISABLE;

DELETE FROM LIGNECOMMANDES
WHERE IDLIGNECOMMANDE = 9102;

ALTER TRIGGER trg_route_lignecommandes_table ENABLE;

BEGIN
    BEGIN
        route_delete_ligne(9102);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -20104 THEN
                RAISE;
            END IF;
    END;

    DELETE FROM ROUTING_LOG
    WHERE IDLIGNECOMMANDE = 9102;
    COMMIT;
END;
/

PROMPT === INSERT direct dans LIGNECOMMANDES : QUANTITE >= 100 doit aller vers SITE1 ===
INSERT INTO LIGNECOMMANDES
    (IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE)
VALUES
    (9102, 1, 1, 150, 0);
COMMIT;

SELECT
    (SELECT COUNT(*) FROM LIGNECOMMANDES WHERE IDLIGNECOMMANDE = 9102) AS NB_CENTRAL,
    (SELECT COUNT(*) FROM LigneCommandes1@site1_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE1,
    (SELECT COUNT(*) FROM LigneCommandes2@site2_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE2
FROM dual;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE
WHERE IDLIGNECOMMANDE = 9102;

PROMPT === UPDATE direct dans LIGNECOMMANDES : QUANTITE < 100 doit deplacer vers SITE2 ===
UPDATE LIGNECOMMANDES
SET QUANTITE = 25,
    IDPRODUIT = 2,
    REMISE = 0.05
WHERE IDLIGNECOMMANDE = 9102;
COMMIT;

SELECT
    (SELECT COUNT(*) FROM LIGNECOMMANDES WHERE IDLIGNECOMMANDE = 9102) AS NB_CENTRAL,
    (SELECT COUNT(*) FROM LigneCommandes1@site1_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE1,
    (SELECT COUNT(*) FROM LigneCommandes2@site2_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE2
FROM dual;

SELECT SITE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE
FROM V_LIGNECOMMANDES_ROUTAGE
WHERE IDLIGNECOMMANDE = 9102;

PROMPT === DELETE direct dans LIGNECOMMANDES : doit supprimer le fragment distant ===
DELETE FROM LIGNECOMMANDES
WHERE IDLIGNECOMMANDE = 9102;
COMMIT;

SELECT
    (SELECT COUNT(*) FROM LIGNECOMMANDES WHERE IDLIGNECOMMANDE = 9102) AS NB_CENTRAL,
    (SELECT COUNT(*) FROM LigneCommandes1@site1_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE1,
    (SELECT COUNT(*) FROM LigneCommandes2@site2_link WHERE IDLIGNECOMMANDE = 9102) AS NB_SITE2
FROM dual;

PROMPT === Journal de routage pour l'ecriture directe ===
SELECT OPERATION, SITE_CIBLE, IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE
FROM ROUTING_LOG
WHERE IDLIGNECOMMANDE = 9102
ORDER BY ID_LOG;
