SET SERVEROUTPUT ON

PROMPT === Test 1 : INSERT direct dans LIGNECOMMANDES (doit etre bloque) ===
BEGIN
    INSERT INTO LIGNECOMMANDES (IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE)
    VALUES (9999, 1, 1, 150, 0);
    DBMS_OUTPUT.PUT_LINE('PROBLEME : insert accepte, doublon possible !');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OK - Insert direct bloque : ' || SQLERRM);
END;
/

PROMPT === Test 2 : INSERT via V_LIGNECOMMANDES_ROUTAGE (doit reussir) ===
BEGIN
    INSERT INTO V_LIGNECOMMANDES_ROUTAGE (IDLIGNECOMMANDE, IDCOMMANDE, IDPRODUIT, QUANTITE, REMISE)
    VALUES (9999, 1, 1, 150, 0);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('OK - Insert via vue reussi, route vers SITE1 (QTE=150 >= 100)');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERREUR vue : ' || SQLERRM);
END;
/

PROMPT === Verification : la ligne 9999 est bien sur SITE1 uniquement ===
SELECT 'SITE1' AS SITE, IDLIGNECOMMANDE, QUANTITE
FROM LigneCommandes1@site1_link
WHERE IDLIGNECOMMANDE = 9999
UNION ALL
SELECT 'SITE2', IDLIGNECOMMANDE, QUANTITE
FROM LigneCommandes2@site2_link
WHERE IDLIGNECOMMANDE = 9999
UNION ALL
SELECT 'CENTRAL', IDLIGNECOMMANDE, QUANTITE
FROM LIGNECOMMANDES
WHERE IDLIGNECOMMANDE = 9999;

PROMPT === Nettoyage ===
BEGIN
    DELETE FROM LigneCommandes1@site1_link WHERE IDLIGNECOMMANDE = 9999;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('OK - Nettoyage effectue');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

EXIT;
